# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Stock Selection

on:
  workflow_dispatch:
  schedule:
  # 每天北京时间下午 5 点运行
    - cron: "0 9 * * *"

permissions:
  contents: write

jobs:
  stock_daily:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Stock Selection
      run: |
        python run.py daily
        
    - name: MV output to disk directory
      run: |
        mkdir -p disk
        mv *.json disk/
        mkdir -p viz
        mv *.html viz/
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add disk/*  
        git commit -m "Add daily output to disk" 
        git push        
